export enum ActionType {
    SELECT_TOOL = 'SELECT_TOOL',
    MOVE_ITINERARY_POINT = 'MOVE_ITINERARY_POINT',
    ADD_ITINERARY_POINT = 'ADD_ITINERARY_POINT',
    UPDATE_ITINERARY_POINT = 'UPDATE_ITINERARY_POINT',
    REMOVE_ITINERARY_POINT = 'REMOVE_ITINERARY_POINT',
    FOCUS_ITINERARY_POINT = 'FOCUS_ITINERARY_POINT',
    FETCH_ROUTES = 'FETCH_ROUTES',
    FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS',
    FETCH_ROUTES_FAILURE = 'FETCH_ROUTES_FAILURE',
    RESET_ROUTES = 'RESET_ROUTES',
    FETCH_SUGGESTIONS = 'FETCH_SUGGESTIONS',
    FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS',
    FETCH_SUGGESTIONS_FAILURE = 'FETCH_SUGGESTIONS_FAILURE',
    SELECT_SUGGESTION = 'SELECT_SUGGESTION',
    CHANGE_THEME = 'CHANGE_THEME',
    ZOOM_IN = 'ZOOM_IN',
    ZOOM_OUT = 'ZOOM_OUT'
}
