export enum ActionType {
    SELECT_TOOL = 'SELECT_TOOL',
    ADD_ITINERARY_POINT = 'ADD_ITINERARY_POINT',
    REMOVE_ITINERARY_POINT = 'REMOVE_ITINERARY_POINT',
    CHANGE_ITINERARY_POINT_LOCATION = 'CHANGE_ITINERARY_POINT_LOCATION'
}
