export enum ActionType {
    SELECT_TOOL = 'SELECT_TOOL',
    ADD_ITINERARY_POINT = 'ADD_ITINERARY_POINT',
    CHANGE_ITINERARY_POINT_LOCATION = 'CHANGE_ITINERARY_POINT_LOCATION',
    MOVE_ITINERARY_POINT = 'MOVE_ITINERARY_POINT',
    REMOVE_ITINERARY_POINT = 'REMOVE_ITINERARY_POINT',
    FETCH_ROUTES = 'FETCH_ROUTES',
    FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS',
    FETCH_ROUTES_FAILURE = 'FETCH_ROUTES_FAILURE',
    RESET_ROUTES_ACTION = 'RESET_ROUTES_ACTION'
}
